Document: mingw-w64-xz
Title: Debian mingw-w64-xz Manual
Author: <insert document author here>
Abstract: This manual describes what mingw-w64-xz is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mingw-w64-xz/mingw-w64-xz.sgml.gz

Format: postscript
Files: /usr/share/doc/mingw-w64-xz/mingw-w64-xz.ps.gz

Format: text
Files: /usr/share/doc/mingw-w64-xz/mingw-w64-xz.text.gz

Format: HTML
Index: /usr/share/doc/mingw-w64-xz/html/index.html
Files: /usr/share/doc/mingw-w64-xz/html/*.html
